backend:
  name: git-gateway

media_folder: public/images
public_folder: /images

collections:
  - label: posts
    name: Posts
    folder: content/posts
    create: true
    slug: "{{slug}}"
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Description, name: description, widget: text, required: false}
      - {label: Language, name: language, widget: select, options: [{label: English, value: en}, {label: German, value: de}, {label: فارسی, value: fa}], default: en}
      - {label: Tags, name: tags, widget: list, required: false}
      - {label: Hero Image, name: hero_image, widget: image, required: false}
      - {label: Draft, name: draft, widget: boolean, required: false}
      - {label: Date, name: date, widget: datetime}
      - {label: Body, name: body, widget: markdown}

  - label: Pages
    name: pages
    files: 
      - label: Portfolio
        name: portfolio
        file: content/pages/portfolio.json
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Description, name: description, widget: text, required: false}
          - label: Projects
            name: projects
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Description, name: description, widget: text, required: false}
              - {label: Link, name: link, widget: string, required: false}
              - {label: Image, name: image, widget: image, required: false}
              - {label: Tags, name: tags, widget: list, required: false}
              - {label: Date, name: date, widget: datetime}
              - {label: Body, name: body, widget: markdown}

      - label: CV
        name: cv
        file: content/pages/cv.json
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Description, name: description, widget: text, required: false}
          - {label: Body, name: body, widget: markdown}
          - label: Educations
            name: educations
            widget: list
            fields:
              - {label: Award Title, name: title, widget: string}
              - {label: Start Date, name: start_date, widget: date}
              - {label: End Date, name: end_date, widget: date, required: false}
              - label: Organization
                name: organization
                widget: object
                fields:
                  - {label: Name, name: name, widget: string}
                  - {label: Icon, name: icon, widget: image, required: false}
                  - {label: Address, name: address, widget: text, required: false}
                  - {label: Website, name: website, widget: string, required: false}
              - {label: Description, name: description, widget: markdown}
          - label: Experiences
            name: experiences
            widget: list
            fields:
              - {label: Job Title, name: title, widget: string}
              - {label: Start Date, name: start_date, widget: date}
              - {label: End Date, name: end_date, widget: date, required: false}
              - label: Organization
                name: organization
                widget: object
                fields:
                  - {label: Name, name: name, widget: string}
                  - {label: Icon, name: icon, widget: image, required: false}
                  - {label: Address, name: address, widget: text, required: false}
                  - {label: Website, name: website, widget: string, required: false}
              - {label: Job Description, name: description, widget: markdown}

